# Generated by Django 2.1.1 on 2018-10-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('mail', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=10)),
                ('contrasenia', models.CharField(max_length=30)),
            ],
        ),
    ]
