# Generated by Django 2.1.1 on 2018-11-03 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_tipousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('num_serie', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('fecha_compra', models.DateField()),
                ('precio_dia', models.FloatField()),
                ('unidad_medida', models.CharField(choices=[('P', 'Pulsos'), ('D', 'Dias')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('informacion', models.CharField(max_length=2000)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Equipo')),
            ],
        ),
    ]
