# Generated by Django 2.1.1 on 2018-11-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_equipo_tratamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='num_serie',
            field=models.IntegerField(error_messages={'unique': 'Ya existe un equipo con este numero de serie'}, primary_key=True, serialize=False, unique=True),
        ),
    ]
