# Generated by Django 2.1.1 on 2018-11-03 19:56

from django.db import migrations, models
import gestion.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_auto_20181103_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fecha_compra',
            field=models.DateField(validators=[gestion.models.no_future]),
        ),
    ]
