# Generated by Django 2.1.1 on 2018-11-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_equipo_periodo_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='periodo_mantenimiento',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='precio_dia',
            field=models.PositiveIntegerField(),
        ),
    ]
