# Generated by Django 2.1.1 on 2018-11-03 20:09

from django.db import migrations, models
import gestion.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_auto_20181103_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='periodo_mantenimiento',
            field=models.IntegerField(validators=[gestion.models.negativo]),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='precio_dia',
            field=models.IntegerField(validators=[gestion.models.negativo]),
        ),
    ]
