# Generated by Django 2.1.1 on 2018-11-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_auto_20181103_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamiento',
            name='equipo',
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe un tratamiento con este nombre'}, max_length=50, unique=True),
        ),
    ]
