# Generated by Django 2.1.1 on 2018-11-07 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_auto_20181103_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='dni',
            field=models.IntegerField(error_messages={'unique': 'Ya existe un usuario con este DNI'}, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='nombre',
            field=models.CharField(max_length=70),
        ),
    ]
