# Generated by Django 2.1.1 on 2018-11-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_auto_20181107_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
