# Generated by Django 2.1.1 on 2018-11-10 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_auto_20181107_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioPorUso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('rango', models.BigIntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Equipo')),
            ],
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='usuario',
            field=models.CharField(error_messages={'unique': 'Ya existe un tecnico con ese usuario'}, max_length=10, unique=True),
        ),
    ]
