# Generated by Django 2.1.1 on 2018-11-10 21:42

from django.db import migrations, models
import gestion.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_auto_20181110_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precioporuso',
            name='precio',
            field=models.FloatField(validators=[gestion.models.negativo]),
        ),
        migrations.AlterField(
            model_name='precioporuso',
            name='rango',
            field=models.BigIntegerField(validators=[gestion.models.negativo]),
        ),
    ]
