# Generated by Django 2.1.1 on 2018-11-10 21:47

from django.db import migrations, models
import gestion.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_auto_20181110_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precioporuso',
            name='precio',
            field=models.FloatField(validators=[gestion.models.negativo]),
        ),
        migrations.AlterField(
            model_name='precioporuso',
            name='rango',
            field=models.BigIntegerField(error_messages={'unique': 'Ya existe ese rango para el equipo'}, unique=True, validators=[gestion.models.negativo]),
        ),
    ]
