# Generated by Django 2.1.1 on 2018-11-10 21:49

from django.db import migrations, models
import gestion.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_auto_20181110_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precioporuso',
            name='rango',
            field=models.BigIntegerField(validators=[gestion.models.negativo]),
        ),
    ]
