# Generated by Django 2.1.1 on 2018-11-16 15:23

from django.db import migrations, models
import django.db.models.deletion
import gestion.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_auto_20181110_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateField(validators=[gestion.models.no_past])),
                ('hasta', models.DateField(validators=[gestion.models.no_past])),
                ('estado', models.CharField(choices=[('R', 'Reservado'), ('C', 'Confirmado'), ('E', 'En curso'), ('O', 'Cancelado'), ('F', 'Finalizado')], max_length=1)),
                ('estado_inicial', models.BigIntegerField(blank=True, null=True, validators=[gestion.models.negativo])),
                ('estado_final', models.BigIntegerField(blank=True, null=True, validators=[gestion.models.negativo])),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Equipo')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.Tecnico')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoTratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Equipo')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Tratamiento')),
            ],
        ),
    ]
