# Generated by Django 2.1.1 on 2018-11-11 16:58

from django.db import migrations, models
import django.db.models.deletion
import gestion.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_equipotratamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateField(validators=[gestion.models.no_past])),
                ('hasta', models.DateField(validators=[gestion.models.no_past])),
                ('estado', models.CharField(blank=True, choices=[('R', 'Reservado'), ('C', 'Confirmado'), ('E', 'En curso'), ('O', 'Cancelado'), ('F', 'Finalizado')], max_length=1, null=True)),
                ('estado_inicial', models.BigIntegerField(validators=[gestion.models.negativo])),
                ('estado_final', models.BigIntegerField(blank=True, null=True, validators=[gestion.models.negativo])),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Equipo')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Tecnico')),
            ],
        ),
    ]
