# Generated by Django 2.1.1 on 2018-11-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_alquiler_equipotratamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.CharField(choices=[('C', 'Candela'), ('V', 'Venus Legacy')], max_length=1),
        ),
    ]
