# Generated by Django 2.1.1 on 2018-11-11 18:55

from django.db import migrations, models
import django.db.models.deletion
import gestion.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_alquiler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('R', 'Reservado'), ('C', 'Confirmado'), ('E', 'En curso'), ('O', 'Cancelado'), ('F', 'Finalizado')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='estado_inicial',
            field=models.BigIntegerField(blank=True, null=True, validators=[gestion.models.negativo]),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.Tecnico'),
        ),
    ]
