# Generated by Django 2.1.1 on 2018-11-16 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_auto_20181111_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipotratamiento',
            name='equipo',
        ),
        migrations.RemoveField(
            model_name='equipotratamiento',
            name='tratamiento',
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='equipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.Equipo'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EquipoTratamiento',
        ),
    ]
