# Generated by Django 2.1.1 on 2018-11-19 20:27

from django.db import migrations, models
import django.db.models.deletion
import gestion.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_auto_20181119_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(validators=[gestion.models.no_past])),
                ('Tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Tratamiento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.Cliente')),
            ],
        ),
    ]
