# Generated by Django 2.1.1 on 2018-11-19 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0022_turno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='Tratamiento',
            new_name='tratamiento',
        ),
    ]
