# Generated by Django 2.1.1 on 2018-11-25 17:43

from django.db import migrations, models
import gestion.models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0025_auto_20181120_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='pagado',
            field=models.FloatField(blank=True, null=True, validators=[gestion.models.negativo]),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='precio',
            field=models.FloatField(default=10, validators=[gestion.models.negativo]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alquiler',
            name='precio_exceso',
            field=models.FloatField(blank=True, null=True, validators=[gestion.models.negativo]),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='estado',
            field=models.CharField(choices=[('R', 'Reservado'), ('C', 'Confirmado'), ('S', 'Esperando Confirmacion'), ('E', 'En curso'), ('O', 'Cancelado'), ('F', 'Finalizado'), ('P', 'Pagado')], max_length=1),
        ),
    ]
